<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Voucher_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->voucher_id	= 'ID';
		$this->voucher_nama_voucher	= 'NAMA_VOUCHER';
		$this->voucher_channel_payment	= 'CHANNEL_PAYMENT';
		$this->voucher_jenis_pembayaran	= 'JENIS_PEMBAYARAN';
		$this->voucher_jenis_cashback	= 'JENIS_CASHBACK';
		$this->voucher_percent_cashback	= 'PERCENT_CASHBACK';
		$this->voucher_nominal_cashback	= 'NOMINAL_CASHBACK';
		$this->voucher_max_nominal	= 'MAX_NOMINAL';
		$this->voucher_start_datelive	= 'START_DATELIVE';
		$this->voucher_end_datelive	= 'END_DATELIVE';
		$this->voucher_wording	= 'WORDING';
		$this->voucher_image	= 'IMAGE';
		$this->voucher_kode_voucher	= 'KODE_VOUCHER';
		$this->voucher_is_active	= 'IS_ACTIVE';
		$this->voucher_already_subscribe	= 'ALREADY_SUBSCRIBE';
		$this->voucher_periode_time	= 'PERIODE_TIME';
		$this->voucher_special_day	= 'SPECIAL_DAY';
		$this->voucher_special_day_date	= 'SPECIAL_DAY_DATE';
		$this->voucher_minimum_payment	= 'MINIMUM_PAYMENT';
		$this->voucher_regional	= 'REGIONAL';
		$this->voucher_witel	= 'WITEL';
		$this->voucher_addon	= 'ADDON';
		$this->voucher_type_customer	= 'TYPE_CUSTOMER';
		$this->voucher_type_hvc	= 'TYPE_HVC';
		$this->voucher_islimited	= 'ISLIMITED';
		$this->voucher_limit_voucher	= 'LIMIT_VOUCHER';
		$this->voucher_user_input	= 'USER_INPUT';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama_voucher	= 'nama_voucher';
		$this->f_channel_payment	= 'channel_payment';
		$this->f_jenis_pembayaran	= 'jenis_pembayaran';
		$this->f_jenis_cashback	= 'jenis_cashback';
		$this->f_percent_cashback	= 'percent_cashback';
		$this->f_nominal_cashback	= 'nominal_cashback';
		$this->f_max_nominal	= 'max_nominal';
		$this->f_start_datelive	= 'start_datelive';
		$this->f_end_datelive	= 'end_datelive';
		$this->f_wording	= 'wording';
		$this->f_image	= 'image';
		$this->f_kode_voucher	= 'kode_voucher';
		$this->f_is_active	= 'is_active';
		$this->f_already_subscribe	= 'already_subscribe';
		$this->f_periode_time	= 'periode_time';
		$this->f_special_day	= 'special_day';
		$this->f_special_day_date	= 'special_day_date';
		$this->f_minimum_payment	= 'minimum_payment';
		$this->f_regional	= 'regional';
		$this->f_witel	= 'witel';
		$this->f_addon	= 'addon';
		$this->f_type_customer	= 'type_customer';
		$this->f_type_hvc	= 'type_hvc';
		$this->f_islimited	= 'islimited';
		$this->f_limit_voucher	= 'limit_voucher';
		$this->f_user_input	= 'user_input';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->voucher_id,
			$this->f_nama_voucher	=> $this->voucher_nama_voucher,
			$this->f_channel_payment	=> $this->voucher_channel_payment,
			$this->f_jenis_pembayaran	=> $this->voucher_jenis_pembayaran,
			$this->f_jenis_cashback	=> $this->voucher_jenis_cashback,
			$this->f_percent_cashback	=> $this->voucher_percent_cashback,
			$this->f_nominal_cashback	=> $this->voucher_nominal_cashback,
			$this->f_max_nominal	=> $this->voucher_max_nominal,
			$this->f_start_datelive	=> $this->voucher_start_datelive,
			$this->f_end_datelive	=> $this->voucher_end_datelive,
			$this->f_wording	=> $this->voucher_wording,
			$this->f_image	=> $this->voucher_image,
			$this->f_kode_voucher	=> $this->voucher_kode_voucher,
			$this->f_is_active	=> $this->voucher_is_active,
			$this->f_already_subscribe	=> $this->voucher_already_subscribe,
			$this->f_periode_time	=> $this->voucher_periode_time,
			$this->f_special_day	=> $this->voucher_special_day,
			$this->f_special_day_date	=> $this->voucher_special_day_date,
			$this->f_minimum_payment	=> $this->voucher_minimum_payment,
			$this->f_regional	=> $this->voucher_regional,
			$this->f_witel	=> $this->voucher_witel,
			$this->f_addon	=> $this->voucher_addon,
			$this->f_type_customer	=> $this->voucher_type_customer,
			$this->f_type_hvc	=> $this->voucher_type_hvc,
			$this->f_islimited	=> $this->voucher_islimited,
			$this->f_limit_voucher	=> $this->voucher_limit_voucher,
			$this->f_user_input	=> $this->voucher_user_input,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-10-14 10:06:38 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

