<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_channel_payment_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->t_channel_payment_id	= 'ID';
		$this->t_channel_payment_nama_channel	= 'NAMA_CHANNEL';
		$this->t_channel_payment_desc	= 'DESC';
		$this->t_channel_payment_image	= 'IMAGE';
		$this->t_channel_payment_category	= 'CATEGORY';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama_channel	= 'nama_channel';
		$this->f_desc	= 'desc';
		$this->f_image	= 'image';
		$this->f_category	= 'category';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->t_channel_payment_id,
			$this->f_nama_channel	=> $this->t_channel_payment_nama_channel,
			$this->f_desc	=> $this->t_channel_payment_desc,
			$this->f_image	=> $this->t_channel_payment_image,
			$this->f_category	=> $this->t_channel_payment_category,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-09-28 09:05:19 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

